// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;
public class test1 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void untitled() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(1054, 848));
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
        driver.getCurrentUrl();
        assertEquals("https://www.saucedemo.com/inventory.html",driver.getCurrentUrl());

        driver.findElement(By.cssSelector(".inventory_item:nth-child(1) .inventory_item_desc")).getText();
        assertEquals("carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.",
                driver.findElement(By.cssSelector(".inventory_item:nth-child(1) .inventory_item_desc")).getText());

        driver.findElement(By.cssSelector(".inventory_item:nth-child(2) .inventory_item_desc")).getText();
        assertEquals("A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.",
                driver.findElement(By.cssSelector(".inventory_item:nth-child(2) .inventory_item_desc")).getText());
    }
}
